### ISSUE TITLE
anaconda upload --description does nothing.

### ISSUE THREAD

**Issue by mforbes** [Anaconda-Platform/anaconda-client#517]
Specifying the `--description` with `anaconda upload` does nothing.  I expected it would set the description for the environment, but it appears to be ignored.

It would be very convenient if environment metadata such as the description could be included and read from the environment file.  I.e. 

```yml
# environment.yml
name: py3
description:
    Bare python 3 environment.
dependencies:
  - python=3
```

Then, a simple

```bash
anaconda upload -f environment.yml
```

would be equivalent to

```bash
anaconda upload -f environment.yml --description "Bare python 3 environment."
```

(which does not work anyway as per this issue).
